### ISSUE TITLE
 Error processing Instruction 0: custom program error: 0x63

### ISSUE THREAD

**Issue by AuroraLantean** [Henry-E/dog-money#1]
Hi Henry, I downloaded your code then installed some nodeJs packages, then fixed the Anchor.toml file, then when I run "anchor test", it can compile the program no problem, but then it failed:
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x63
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:4882:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Connection.sendRawTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:4841:20)
      at async Object.sendAndConfirmRawTransaction (node_modules/@solana/web3.js/lib/index.cjs.js:6668:21)
      at async Provider.send (node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
      at async Object.rpc [as initializeUser] (node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
      at async Context.<anonymous> (tests/dog-money.js:52:5)
tests/dog-money.js:52 has code:  await program.rpc.initializeUser(amount, nonce, {
could you please help? Thanks

**Comment by Henry-E** [comment]
https://www.notion.so/Debugging-Custom-Anchor-Errors-b8540dd418c44a4e939ab17c56a3fd3b

0x63 converts to 99

It would be helpful to know what the program is that's failing?

There's no 99 error code in either anchor or the token program. So it's likely you're on an older version of anchor (as is the original dog money code unfortunately).
